/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ch_imetrica_mdfa_ZPCFilter */

#ifndef _Included_ch_imetrica_mdfa_ZPCFilter
#define _Included_ch_imetrica_mdfa_ZPCFilter
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ch_imetrica_mdfa_ZPCFilter
 * Method:    optimizeZPC
 * Signature: ([DIIIII[DDDDDDDIDDD)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_ch_imetrica_mdfa_ZPCFilter_optimizeZPC
  (JNIEnv *, jobject, jdoubleArray, jint, jint, jint, jint, jint, jdoubleArray, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jint, jdouble, jdouble, jdouble);

/*
 * Class:     ch_imetrica_mdfa_ZPCFilter
 * Method:    _computeGridZPC
 * Signature: ([DIIIII[DDDDDDDIDDIDDDI)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_ch_imetrica_mdfa_ZPCFilter__1computeGridZPC
  (JNIEnv *, jobject, jdoubleArray, jint, jint, jint, jint, jint, jdoubleArray, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jint, jdouble, jdouble, jint, jdouble, jdouble, jdouble, jint);

#ifdef __cplusplus
}
#endif
#endif
