/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ch_imetrica_usimx13_SARIMAmodelJava */

#ifndef _Included_ch_imetrica_usimx13_SARIMAmodelJava
#define _Included_ch_imetrica_usimx13_SARIMAmodelJava
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ch_imetrica_usimx13_SARIMAmodelJava
 * Method:    getSigExDiagnostics
 * Signature: ([D[I[DIIIIZ)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_ch_imetrica_usimx13_SARIMAmodelJava_getSigExDiagnostics
  (JNIEnv *, jobject, jdoubleArray, jintArray, jdoubleArray, jint, jint, jint, jint, jboolean);

/*
 * Class:     ch_imetrica_usimx13_SARIMAmodelJava
 * Method:    computeMinimumSarima
 * Signature: ([I[D[I)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_ch_imetrica_usimx13_SARIMAmodelJava_computeMinimumSarima
  (JNIEnv *, jobject, jintArray, jdoubleArray, jintArray);

/*
 * Class:     ch_imetrica_usimx13_SARIMAmodelJava
 * Method:    getEfficacies
 * Signature: (I[D[I[DI[IIII)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_ch_imetrica_usimx13_SARIMAmodelJava_getEfficacies
  (JNIEnv *, jobject, jint, jdoubleArray, jintArray, jdoubleArray, jint, jintArray, jint, jint, jint);

/*
 * Class:     ch_imetrica_usimx13_SARIMAmodelJava
 * Method:    getSARIMAmodel
 * Signature: (II[D[IIII)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_ch_imetrica_usimx13_SARIMAmodelJava_getSARIMAmodel
  (JNIEnv *, jobject, jint, jint, jdoubleArray, jintArray, jint, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
