/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ch_imetrica_dataControl_SimPanel */

#ifndef _Included_ch_imetrica_dataControl_SimPanel
#define _Included_ch_imetrica_dataControl_SimPanel
#ifdef __cplusplus
extern "C" {
#endif
#undef ch_imetrica_dataControl_SimPanel_FOCUS_TRAVERSABLE_UNKNOWN
#define ch_imetrica_dataControl_SimPanel_FOCUS_TRAVERSABLE_UNKNOWN 0L
#undef ch_imetrica_dataControl_SimPanel_FOCUS_TRAVERSABLE_DEFAULT
#define ch_imetrica_dataControl_SimPanel_FOCUS_TRAVERSABLE_DEFAULT 1L
#undef ch_imetrica_dataControl_SimPanel_FOCUS_TRAVERSABLE_SET
#define ch_imetrica_dataControl_SimPanel_FOCUS_TRAVERSABLE_SET 2L
#undef ch_imetrica_dataControl_SimPanel_TOP_ALIGNMENT
#define ch_imetrica_dataControl_SimPanel_TOP_ALIGNMENT 0.0f
#undef ch_imetrica_dataControl_SimPanel_CENTER_ALIGNMENT
#define ch_imetrica_dataControl_SimPanel_CENTER_ALIGNMENT 0.5f
#undef ch_imetrica_dataControl_SimPanel_BOTTOM_ALIGNMENT
#define ch_imetrica_dataControl_SimPanel_BOTTOM_ALIGNMENT 1.0f
#undef ch_imetrica_dataControl_SimPanel_LEFT_ALIGNMENT
#define ch_imetrica_dataControl_SimPanel_LEFT_ALIGNMENT 0.0f
#undef ch_imetrica_dataControl_SimPanel_RIGHT_ALIGNMENT
#define ch_imetrica_dataControl_SimPanel_RIGHT_ALIGNMENT 1.0f
#undef ch_imetrica_dataControl_SimPanel_serialVersionUID
#define ch_imetrica_dataControl_SimPanel_serialVersionUID -7644114512714619750LL
#undef ch_imetrica_dataControl_SimPanel_serialVersionUID
#define ch_imetrica_dataControl_SimPanel_serialVersionUID 4613797578919906343LL
#undef ch_imetrica_dataControl_SimPanel_INCLUDE_SELF
#define ch_imetrica_dataControl_SimPanel_INCLUDE_SELF 1L
#undef ch_imetrica_dataControl_SimPanel_SEARCH_HEAVYWEIGHTS
#define ch_imetrica_dataControl_SimPanel_SEARCH_HEAVYWEIGHTS 1L
#undef ch_imetrica_dataControl_SimPanel_NOT_OBSCURED
#define ch_imetrica_dataControl_SimPanel_NOT_OBSCURED 0L
#undef ch_imetrica_dataControl_SimPanel_PARTIALLY_OBSCURED
#define ch_imetrica_dataControl_SimPanel_PARTIALLY_OBSCURED 1L
#undef ch_imetrica_dataControl_SimPanel_COMPLETELY_OBSCURED
#define ch_imetrica_dataControl_SimPanel_COMPLETELY_OBSCURED 2L
#undef ch_imetrica_dataControl_SimPanel_WHEN_FOCUSED
#define ch_imetrica_dataControl_SimPanel_WHEN_FOCUSED 0L
#undef ch_imetrica_dataControl_SimPanel_WHEN_ANCESTOR_OF_FOCUSED_COMPONENT
#define ch_imetrica_dataControl_SimPanel_WHEN_ANCESTOR_OF_FOCUSED_COMPONENT 1L
#undef ch_imetrica_dataControl_SimPanel_WHEN_IN_FOCUSED_WINDOW
#define ch_imetrica_dataControl_SimPanel_WHEN_IN_FOCUSED_WINDOW 2L
#undef ch_imetrica_dataControl_SimPanel_UNDEFINED_CONDITION
#define ch_imetrica_dataControl_SimPanel_UNDEFINED_CONDITION -1L
#undef ch_imetrica_dataControl_SimPanel_IS_DOUBLE_BUFFERED
#define ch_imetrica_dataControl_SimPanel_IS_DOUBLE_BUFFERED 0L
#undef ch_imetrica_dataControl_SimPanel_ANCESTOR_USING_BUFFER
#define ch_imetrica_dataControl_SimPanel_ANCESTOR_USING_BUFFER 1L
#undef ch_imetrica_dataControl_SimPanel_IS_PAINTING_TILE
#define ch_imetrica_dataControl_SimPanel_IS_PAINTING_TILE 2L
#undef ch_imetrica_dataControl_SimPanel_IS_OPAQUE
#define ch_imetrica_dataControl_SimPanel_IS_OPAQUE 3L
#undef ch_imetrica_dataControl_SimPanel_KEY_EVENTS_ENABLED
#define ch_imetrica_dataControl_SimPanel_KEY_EVENTS_ENABLED 4L
#undef ch_imetrica_dataControl_SimPanel_FOCUS_INPUTMAP_CREATED
#define ch_imetrica_dataControl_SimPanel_FOCUS_INPUTMAP_CREATED 5L
#undef ch_imetrica_dataControl_SimPanel_ANCESTOR_INPUTMAP_CREATED
#define ch_imetrica_dataControl_SimPanel_ANCESTOR_INPUTMAP_CREATED 6L
#undef ch_imetrica_dataControl_SimPanel_WIF_INPUTMAP_CREATED
#define ch_imetrica_dataControl_SimPanel_WIF_INPUTMAP_CREATED 7L
#undef ch_imetrica_dataControl_SimPanel_ACTIONMAP_CREATED
#define ch_imetrica_dataControl_SimPanel_ACTIONMAP_CREATED 8L
#undef ch_imetrica_dataControl_SimPanel_CREATED_DOUBLE_BUFFER
#define ch_imetrica_dataControl_SimPanel_CREATED_DOUBLE_BUFFER 9L
#undef ch_imetrica_dataControl_SimPanel_IS_PRINTING
#define ch_imetrica_dataControl_SimPanel_IS_PRINTING 11L
#undef ch_imetrica_dataControl_SimPanel_IS_PRINTING_ALL
#define ch_imetrica_dataControl_SimPanel_IS_PRINTING_ALL 12L
#undef ch_imetrica_dataControl_SimPanel_IS_REPAINTING
#define ch_imetrica_dataControl_SimPanel_IS_REPAINTING 13L
#undef ch_imetrica_dataControl_SimPanel_WRITE_OBJ_COUNTER_FIRST
#define ch_imetrica_dataControl_SimPanel_WRITE_OBJ_COUNTER_FIRST 14L
#undef ch_imetrica_dataControl_SimPanel_RESERVED_1
#define ch_imetrica_dataControl_SimPanel_RESERVED_1 15L
#undef ch_imetrica_dataControl_SimPanel_RESERVED_2
#define ch_imetrica_dataControl_SimPanel_RESERVED_2 16L
#undef ch_imetrica_dataControl_SimPanel_RESERVED_3
#define ch_imetrica_dataControl_SimPanel_RESERVED_3 17L
#undef ch_imetrica_dataControl_SimPanel_RESERVED_4
#define ch_imetrica_dataControl_SimPanel_RESERVED_4 18L
#undef ch_imetrica_dataControl_SimPanel_RESERVED_5
#define ch_imetrica_dataControl_SimPanel_RESERVED_5 19L
#undef ch_imetrica_dataControl_SimPanel_RESERVED_6
#define ch_imetrica_dataControl_SimPanel_RESERVED_6 20L
#undef ch_imetrica_dataControl_SimPanel_WRITE_OBJ_COUNTER_LAST
#define ch_imetrica_dataControl_SimPanel_WRITE_OBJ_COUNTER_LAST 21L
#undef ch_imetrica_dataControl_SimPanel_REQUEST_FOCUS_DISABLED
#define ch_imetrica_dataControl_SimPanel_REQUEST_FOCUS_DISABLED 22L
#undef ch_imetrica_dataControl_SimPanel_INHERITS_POPUP_MENU
#define ch_imetrica_dataControl_SimPanel_INHERITS_POPUP_MENU 23L
#undef ch_imetrica_dataControl_SimPanel_OPAQUE_SET
#define ch_imetrica_dataControl_SimPanel_OPAQUE_SET 24L
#undef ch_imetrica_dataControl_SimPanel_AUTOSCROLLS_SET
#define ch_imetrica_dataControl_SimPanel_AUTOSCROLLS_SET 25L
#undef ch_imetrica_dataControl_SimPanel_FOCUS_TRAVERSAL_KEYS_FORWARD_SET
#define ch_imetrica_dataControl_SimPanel_FOCUS_TRAVERSAL_KEYS_FORWARD_SET 26L
#undef ch_imetrica_dataControl_SimPanel_FOCUS_TRAVERSAL_KEYS_BACKWARD_SET
#define ch_imetrica_dataControl_SimPanel_FOCUS_TRAVERSAL_KEYS_BACKWARD_SET 27L
#undef ch_imetrica_dataControl_SimPanel_serialVersionUID
#define ch_imetrica_dataControl_SimPanel_serialVersionUID 1LL
/*
 * Class:     ch_imetrica_dataControl_SimPanel
 * Method:    crossCorrelation
 * Signature: (I[D[D)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_ch_imetrica_dataControl_SimPanel_crossCorrelation
  (JNIEnv *, jobject, jint, jdoubleArray, jdoubleArray);

/*
 * Class:     ch_imetrica_dataControl_SimPanel
 * Method:    fsv
 * Signature: (IIDDDDDI)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_ch_imetrica_dataControl_SimPanel_fsv
  (JNIEnv *, jobject, jint, jint, jdouble, jdouble, jdouble, jdouble, jdouble, jint);

/*
 * Class:     ch_imetrica_dataControl_SimPanel
 * Method:    isv
 * Signature: (IDDDI)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_ch_imetrica_dataControl_SimPanel_isv
  (JNIEnv *, jobject, jint, jdouble, jdouble, jdouble, jint);

/*
 * Class:     ch_imetrica_dataControl_SimPanel
 * Method:    sarima
 * Signature: (II[D[IIIII)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_ch_imetrica_dataControl_SimPanel_sarima
  (JNIEnv *, jobject, jint, jint, jdoubleArray, jintArray, jint, jint, jint, jint);

/*
 * Class:     ch_imetrica_dataControl_SimPanel
 * Method:    GARCH
 * Signature: (IIII[DI)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_ch_imetrica_dataControl_SimPanel_GARCH
  (JNIEnv *, jobject, jint, jint, jint, jint, jdoubleArray, jint);

/*
 * Class:     ch_imetrica_dataControl_SimPanel
 * Method:    nGARCH
 * Signature: (II[DI)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_ch_imetrica_dataControl_SimPanel_nGARCH
  (JNIEnv *, jobject, jint, jint, jdoubleArray, jint);

/*
 * Class:     ch_imetrica_dataControl_SimPanel
 * Method:    cycles
 * Signature: (IIIDDDI)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_ch_imetrica_dataControl_SimPanel_cycles
  (JNIEnv *, jobject, jint, jint, jint, jdouble, jdouble, jdouble, jint);

/*
 * Class:     ch_imetrica_dataControl_SimPanel
 * Method:    plotData
 * Signature: ([DI)V
 */
JNIEXPORT void JNICALL Java_ch_imetrica_dataControl_SimPanel_plotData
  (JNIEnv *, jclass, jdoubleArray, jint);

/*
 * Class:     ch_imetrica_dataControl_SimPanel
 * Method:    plotData2
 * Signature: ([D[DI)V
 */
JNIEXPORT void JNICALL Java_ch_imetrica_dataControl_SimPanel_plotData2
  (JNIEnv *, jclass, jdoubleArray, jdoubleArray, jint);

#ifdef __cplusplus
}
#endif
#endif
