/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ch_imetrica_bayesCronos_Cronos */

#ifndef _Included_ch_imetrica_bayesCronos_Cronos
#define _Included_ch_imetrica_bayesCronos_Cronos
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ch_imetrica_bayesCronos_Cronos
 * Method:    computeARIMA
 * Signature: ([D[DIIDIII[D[D[D[D[D)V
 */
JNIEXPORT void JNICALL Java_ch_imetrica_bayesCronos_Cronos_computeARIMA
  (JNIEnv *, jobject, jdoubleArray, jdoubleArray, jint, jint, jdouble, jint, jint, jint, jdoubleArray, jdoubleArray, jdoubleArray, jdoubleArray, jdoubleArray);

/*
 * Class:     ch_imetrica_bayesCronos_Cronos
 * Method:    computeBayesianARIMA
 * Signature: ([D[DIIDIIIII[D[D[D[D[D[D)V
 */
JNIEXPORT void JNICALL Java_ch_imetrica_bayesCronos_Cronos_computeBayesianARIMA
  (JNIEnv *, jobject, jdoubleArray, jdoubleArray, jint, jint, jdouble, jint, jint, jint, jint, jint, jdoubleArray, jdoubleArray, jdoubleArray, jdoubleArray, jdoubleArray, jdoubleArray);

/*
 * Class:     ch_imetrica_bayesCronos_Cronos
 * Method:    computeARIMAForecast
 * Signature: ([DIIDIII[D[DDD[D[D[D)V
 */
JNIEXPORT void JNICALL Java_ch_imetrica_bayesCronos_Cronos_computeARIMAForecast
  (JNIEnv *, jobject, jdoubleArray, jint, jint, jdouble, jint, jint, jint, jdoubleArray, jdoubleArray, jdouble, jdouble, jdoubleArray, jdoubleArray, jdoubleArray);

/*
 * Class:     ch_imetrica_bayesCronos_Cronos
 * Method:    computeGARCH
 * Signature: ([D[DIIIII[D[D[D[D[D)V
 */
JNIEXPORT void JNICALL Java_ch_imetrica_bayesCronos_Cronos_computeGARCH
  (JNIEnv *, jobject, jdoubleArray, jdoubleArray, jint, jint, jint, jint, jint, jdoubleArray, jdoubleArray, jdoubleArray, jdoubleArray, jdoubleArray);

/*
 * Class:     ch_imetrica_bayesCronos_Cronos
 * Method:    computeBayesianGARCH
 * Signature: ([D[DIIIIIII[D[D[D[D[D[D)V
 */
JNIEXPORT void JNICALL Java_ch_imetrica_bayesCronos_Cronos_computeBayesianGARCH
  (JNIEnv *, jobject, jdoubleArray, jdoubleArray, jint, jint, jint, jint, jint, jint, jint, jdoubleArray, jdoubleArray, jdoubleArray, jdoubleArray, jdoubleArray, jdoubleArray);

/*
 * Class:     ch_imetrica_bayesCronos_Cronos
 * Method:    computeEGARCH
 * Signature: ([D[DIIIII[D[D[D[D[D[D)V
 */
JNIEXPORT void JNICALL Java_ch_imetrica_bayesCronos_Cronos_computeEGARCH
  (JNIEnv *, jobject, jdoubleArray, jdoubleArray, jint, jint, jint, jint, jint, jdoubleArray, jdoubleArray, jdoubleArray, jdoubleArray, jdoubleArray, jdoubleArray);

/*
 * Class:     ch_imetrica_bayesCronos_Cronos
 * Method:    computeGARCHForecast
 * Signature: ([DIIIII[D[DD[D[D[D)V
 */
JNIEXPORT void JNICALL Java_ch_imetrica_bayesCronos_Cronos_computeGARCHForecast
  (JNIEnv *, jobject, jdoubleArray, jint, jint, jint, jint, jint, jdoubleArray, jdoubleArray, jdouble, jdoubleArray, jdoubleArray, jdoubleArray);

/*
 * Class:     ch_imetrica_bayesCronos_Cronos
 * Method:    computeEGARCHForecast
 * Signature: ([DIIIII[D[D[DD[D[D[D)V
 */
JNIEXPORT void JNICALL Java_ch_imetrica_bayesCronos_Cronos_computeEGARCHForecast
  (JNIEnv *, jobject, jdoubleArray, jint, jint, jint, jint, jint, jdoubleArray, jdoubleArray, jdoubleArray, jdouble, jdoubleArray, jdoubleArray, jdoubleArray);

/*
 * Class:     ch_imetrica_bayesCronos_Cronos
 * Method:    computeSVM
 * Signature: ([D[DIII[D[D[D[D)V
 */
JNIEXPORT void JNICALL Java_ch_imetrica_bayesCronos_Cronos_computeSVM
  (JNIEnv *, jobject, jdoubleArray, jdoubleArray, jint, jint, jint, jdoubleArray, jdoubleArray, jdoubleArray, jdoubleArray);

/*
 * Class:     ch_imetrica_bayesCronos_Cronos
 * Method:    computeBayesianISV
 * Signature: ([DIIIIDDDI[D[D[D[D)V
 */
JNIEXPORT void JNICALL Java_ch_imetrica_bayesCronos_Cronos_computeBayesianISV
  (JNIEnv *, jobject, jdoubleArray, jint, jint, jint, jint, jdouble, jdouble, jdouble, jint, jdoubleArray, jdoubleArray, jdoubleArray, jdoubleArray);

/*
 * Class:     ch_imetrica_bayesCronos_Cronos
 * Method:    computeBayesianFSV
 * Signature: ([DIIIIIIDDDDDI[D[D[D[D[D[D[D[D)V
 */
JNIEXPORT void JNICALL Java_ch_imetrica_bayesCronos_Cronos_computeBayesianFSV
  (JNIEnv *, jobject, jdoubleArray, jint, jint, jint, jint, jint, jint, jdouble, jdouble, jdouble, jdouble, jdouble, jint, jdoubleArray, jdoubleArray, jdoubleArray, jdoubleArray, jdoubleArray, jdoubleArray, jdoubleArray, jdoubleArray);

/*
 * Class:     ch_imetrica_bayesCronos_Cronos
 * Method:    computeBayesianForecastISV
 * Signature: ([D[DIIIDDD[D)V
 */
JNIEXPORT void JNICALL Java_ch_imetrica_bayesCronos_Cronos_computeBayesianForecastISV
  (JNIEnv *, jobject, jdoubleArray, jdoubleArray, jint, jint, jint, jdouble, jdouble, jdouble, jdoubleArray);

/*
 * Class:     ch_imetrica_bayesCronos_Cronos
 * Method:    sarima
 * Signature: (II[D[IIIII)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_ch_imetrica_bayesCronos_Cronos_sarima
  (JNIEnv *, jobject, jint, jint, jdoubleArray, jintArray, jint, jint, jint, jint);

/*
 * Class:     ch_imetrica_bayesCronos_Cronos
 * Method:    plotHistogram
 * Signature: ([DII)V
 */
JNIEXPORT void JNICALL Java_ch_imetrica_bayesCronos_Cronos_plotHistogram
  (JNIEnv *, jobject, jdoubleArray, jint, jint);

/*
 * Class:     ch_imetrica_bayesCronos_Cronos
 * Method:    sortsims
 * Signature: (I[D[I)V
 */
JNIEXPORT void JNICALL Java_ch_imetrica_bayesCronos_Cronos_sortsims
  (JNIEnv *, jclass, jint, jdoubleArray, jintArray);

#ifdef __cplusplus
}
#endif
#endif
