/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ch_imetrica_bayesCronos_HeavyModel */

#ifndef _Included_ch_imetrica_bayesCronos_HeavyModel
#define _Included_ch_imetrica_bayesCronos_HeavyModel
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ch_imetrica_bayesCronos_HeavyModel
 * Method:    computeHeavyModel
 * Signature: ([DIIII[D[DD[D[D[DII[DI[D[D[D[II)V
 */
JNIEXPORT void JNICALL Java_ch_imetrica_bayesCronos_HeavyModel_computeHeavyModel
  (JNIEnv *, jobject, jdoubleArray, jint, jint, jint, jint, jdoubleArray, jdoubleArray, jdouble, jdoubleArray, jdoubleArray, jdoubleArray, jint, jint, jdoubleArray, jint, jdoubleArray, jdoubleArray, jdoubleArray, jintArray, jint);

/*
 * Class:     ch_imetrica_bayesCronos_HeavyModel
 * Method:    simulateHeavyModel
 * Signature: ([D[DIII[D[D[D[III)V
 */
JNIEXPORT void JNICALL Java_ch_imetrica_bayesCronos_HeavyModel_simulateHeavyModel
  (JNIEnv *, jobject, jdoubleArray, jdoubleArray, jint, jint, jint, jdoubleArray, jdoubleArray, jdoubleArray, jintArray, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
