/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ch_imetrica_regComponent_REGmodelJava */

#ifndef _Included_ch_imetrica_regComponent_REGmodelJava
#define _Included_ch_imetrica_regComponent_REGmodelJava
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ch_imetrica_regComponent_REGmodelJava
 * Method:    getRegCmpnt
 * Signature: ([DI)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_ch_imetrica_regComponent_REGmodelJava_getRegCmpnt
  (JNIEnv *, jobject, jdoubleArray, jint);

/*
 * Class:     ch_imetrica_regComponent_REGmodelJava
 * Method:    plotData2
 * Signature: ([D[DI)V
 */
JNIEXPORT void JNICALL Java_ch_imetrica_regComponent_REGmodelJava_plotData2
  (JNIEnv *, jclass, jdoubleArray, jdoubleArray, jint);

/*
 * Class:     ch_imetrica_regComponent_REGmodelJava
 * Method:    plotData
 * Signature: ([DI)V
 */
JNIEXPORT void JNICALL Java_ch_imetrica_regComponent_REGmodelJava_plotData
  (JNIEnv *, jclass, jdoubleArray, jint);

#ifdef __cplusplus
}
#endif
#endif
