/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ch_imetrica_usimx13_SpectralDensity */

#ifndef _Included_ch_imetrica_usimx13_SpectralDensity
#define _Included_ch_imetrica_usimx13_SpectralDensity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ch_imetrica_usimx13_SpectralDensity
 * Method:    spectral_density
 * Signature: ([DIIZDIZIZD)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_ch_imetrica_usimx13_SpectralDensity_spectral_1density
  (JNIEnv *, jobject, jdoubleArray, jint, jint, jboolean, jdouble, jint, jboolean, jint, jboolean, jdouble);

#ifdef __cplusplus
}
#endif
#endif
